### ISSUE TITLE
Elaborate a bit on installation

### ISSUE THREAD

**Issue by mrvdb** [hashbang/mod_muc_irc#1]
This looks interesting as minimalistic irc gateway, but I guess a bit of extra info is needed to get it going?
- the modifications required you are mentioning
- a couple of notes on installing LuaIRC would be nice (it has no doc whatsoever itself)

**Comment by daurnimator** [comment]
> This looks interesting as minimalistic irc gateway, but I guess a bit of extra info is needed to get it going?

It needs some more work before I can recommend others use it. I only hacked around with it for a few hours. At a bare minimum I want to handle nick changes and define private messaging behaviour.

> - the modifications required you are mentioning

I'm trying to make LuaIRC more cqueues friendly. I have a placeholder issue over at https://github.com/JakobOvrum/LuaIRC/issues/31
For the short term, you should be able to hack it in the same way I did in the irc-bot project in this commit: https://github.com/hashbang/irc-bot/commit/ee658b1b9c2149003a3c059e382f3458631006e3

> - a couple of notes on installing LuaIRC would be nice (it has no doc whatsoever itself)

I thought it had okay docs.... See https://github.com/JakobOvrum/LuaIRC/ and https://jakobovrum.github.io/LuaIRC/doc/modules/irc.html

You can install it via luarocks: https://rocks.moonscript.org/modules/develcuy/luairc

**Comment by mrvdb** [comment]
Thanks, the above is exactly what I needed to get me a couple of steps further.
