### ISSUE TITLE
Did this used to be part of prosody-modules?

### ISSUE THREAD

**Issue by singpolyma** [hashbang/mod_muc_irc#3]
I had though there was one there that did this, but I don't find it now.

Does this module still work only with trunk?

**Comment by RyanSquared** [comment]
> This is a Prosody plugin that allows for XMPP MUC clients to access an IRC server.

**Comment by RyanSquared** [comment]
I don't believe it was a part of prosody-modules.

**Comment by daurnimator** [comment]
> Does this module still work only with trunk?

Yes. it requires the new muc module in trunk.

> I don't believe it was a part of prosody-modules.

Correct. this was never part of prosody-modules.

**Comment by KellerFuchs** [comment]
I don't see the issue in this issue...
